---
  - name: Playbook
    hosts: webservers
    become: yes
    become_user: azureuser
    tasks:
      - name: install nginx
        yum:
          name: httpd
          state: latest
      - name: ensure apache is running
        service:
          name: httpd
          state: started